FacilityMVCnew/Models/ErrorViewModel.cs
using System;

namespace FacilityMVCnew.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FacilityMVCnew/Models/Facility.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace FacilityMVCnew.Models
{
    public class Facility
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required.")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "First name cannot be empty.")]
        public string Name { get; set; }
        public string Address { get; set; }
        [Required(ErrorMessage = "Phone is required.")]
        [Phone]
        public string PhoneNumber { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        public int FacilityStatusId { get; set; }
        public virtual FacilityStatus FacilityStatus { get; set; }

    }
}

FacilityMVCnew/Models/FacilityContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FacilityMVCnew.Models
{
    public class FacilityContext: DbContext
    {
        public DbSet<Facility> Facilities { get; set; }
        public DbSet<FacilityStatus> FacilityStatuses { get; set; }

        public FacilityContext(DbContextOptions<FacilityContext> options)
            : base(options)
        {
            Database.EnsureCreated();
        }

    }
}

FacilityMVCnew/Models/FacilityStatus.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FacilityMVCnew.Models
{
    public class FacilityStatus
    {
        public int FacilityStatusId { get; set; }
        public string Name { get; set; }
    }
}

FacilityMVCnew/Controllers/FacilityController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FacilityMVCnew.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FacilityMVCnew.Controllers
{
    public class FacilityController : Controller
    {
        private readonly ILogger<FacilityController> _logger;

        FacilityContext _context;

        public FacilityController(FacilityContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int? pageNumber)
        {
            var facilities = from s in _context.Facilities.Include(x => x.FacilityStatus)
                           select s;
            
            int pageSize = 10;
            return View(await PaginatedList<Facility>.CreateAsync(facilities.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var facility = await _context.Facilities.FindAsync(id);
            if (facility == null)
            {
                return NotFound();
            }
            StatusesDropDownList(facility.FacilityStatusId);
            return View(facility);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,PhoneNumber,Email,FacilityStatusId")] Facility facility)
        {           
            if (id != facility.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(facility);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    //if (FacilityExists(facility.Id))
                    //{
                    //    return NotFound();
                    //}
                    //else
                    //{
                        throw;
                    //}
                }
                return RedirectToAction("Index");
            }
            StatusesDropDownList(facility.FacilityStatusId);
            return View(facility);
        }

        public IActionResult Create()
        {
            StatusesDropDownList();
            return View();
        }

        private void StatusesDropDownList(object selectedStatus = null)
        {
            var departmentsQuery = from s in _context.FacilityStatuses
                                   orderby s.Name
                                   select s;
            ViewBag.FacilityStatusID = new SelectList(departmentsQuery, "FacilityStatusId", "Name", selectedStatus);                       
        }

        
        [HttpPost]
        public ActionResult Create([Bind("Name,Address,PhoneNumber,Email,FacilityStatusId")]Facility facility)
        {
            if (ModelState.IsValid)
            {
                _context.Facilities.Add(facility);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            StatusesDropDownList(facility.FacilityStatusId);
            return View(facility);
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Facility facility = await _context.Facilities.FirstOrDefaultAsync(p => p.Id == id);
                if (facility != null)
                    return View(facility);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Facility facility = await _context.Facilities.FirstOrDefaultAsync(p => p.Id == id);
                if (facility != null)
                {
                    _context.Facilities.Remove(facility);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }

    }
}

FacilityMVCnew/Views/Facility/Create.cshtml
@model FacilityMVCnew.Models.Facility
@{
    ViewBag.Title = "Create"; 
}

<h1>Create</h1>

<h4>Facility</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="FacilityStatusID">FacilityStatus</label>
                <div class="col-md-10">
                    @Html.DropDownList("FacilityStatusID", String.Empty)
                    @Html.ValidationMessageFor(model => model.FacilityStatus)
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FacilityMVCnew/Views/Facility/Delete.cshtml
@model FacilityMVCnew.Models.Facility
@{
    ViewData["Title"] = "Delete";
}

<div>
    <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>       
    </dl>

    <div>
        <form asp-controller="Facility" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Delete" />
            </div>
        </form>
    </div>
</div>

FacilityMVCnew/Views/Facility/Edit.cshtml
@model FacilityMVCnew.Models.Facility
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Facility</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="FacilityStatusID">FacilityStatus</label>
                <div class="col-md-10">
                    @Html.DropDownList("FacilityStatusID", String.Empty)
                    @Html.ValidationMessageFor(model => model.FacilityStatus)
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FacilityMVCnew/Views/Facility/Index.cshtml
@model PaginatedList<FacilityMVCnew.Models.Facility>
@{
    ViewData["Title"] = "List of Facilities";
}

    <h3>Facilities</h3>
    <a asp-action="Create">Add Facility</a>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Address</th>
            <th>Phone</th>
            <th>Email</th>
            <th>FacilityStatus</th>
            <th></th>
        </tr>
        @foreach (var facility in Model)
        {
            <tr>
                <td>@facility.Name</td>
                <td>@facility.Address</td>
                <td>@facility.PhoneNumber</td>
                <td>@facility.Email</td>
                <td>@facility.FacilityStatus.Name</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@facility.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@facility.Id">Delete</a>
                </td>
            </tr>
        }
    </table>
   @{ var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }

    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @nextDisabled">
        Next
    </a>
   

FacilityMVCnew/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FacilityMVCnew</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FacilityMVCnew</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>               
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FacilityMVCnew
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>